### PR TITLE
Add `runtests` keyword argument to the `create_sysimage` function

### PR DESCRIPTION
**Pull request by DilumAluthge**
This PR provides a convenient way of using a package's `test/runtests.jl` file as a way of generating precompile statements.

It will be the responsibility of the user to make sure that all of the package's test dependencies have been added to the project.

Example usage:
```
julia> PackageCompilerX.create_sysimage([:Foo, :Bar];
                                        sysimage_path="ExampleSysimage.so",
                                        runtests = [:Foo])
```

### CODE REVIEW

**Comment by KristofferC** [comment]
I would rather document how you would do this in your own precompile file, e.g.

```jl
using Package
include(joinpath(pkgdir(Package), "test", "runtests.jl"))
```

**Comment by DilumAluthge** [comment]
Cool, I can make a PR to add something to the docs. What section do you want it to go in?

**Comment by KristofferC** [comment]
Could be a section in the part about creating a sysimage.

**Comment by DilumAluthge** [comment]
https://github.com/KristofferC/PackageCompilerX.jl/pull/85

**Pull request closed without merging**
